// frontend/src/utils/subjectKeywords.js

const subjectKeywords = {
  DSA: [
    "ARRAY", "STRING", "RECURSION", "LINKED", "STACK", "QUEUE",
    "TREE", "GRAPH", "AVL", "BST", "SORTING", "SEARCH", "HEAP", "HASH",
    "KRUSKAL", "PRIM", "DIJKSTRA", "FLOYD", "WARSHALL", "GREEDY",
    "DYNAMIC PROGRAMMING", "BACKTRACKING", "TRIE", "SEGMENT TREE",
    "BINARY TREE", "BINARY SEARCH TREE", "MST", "MINIMUM SPANNING TREE"
  ],
  Java: ["JAVA", "JVM", "JDK", "OOPS"],
  Python: ["PYTHON"],
  JavaScript: ["JAVASCRIPT", "ES6", "PROMISE", "ASYNC"],
  ReactJS: ["REACT", "JSX", "HOOK", "COMPONENT"],
  NodeJS: ["NODE", "EXPRESS", "NPM"],
  DBMS: ["DBMS", "SQL", "NORMALIZATION", "DATABASE"],
  "OPERATING SYSTEMS": [
    "OPERATING SYSTEM", "DEADLOCK", "CPU SCHEDULING",
    "PROCESS SCHEDULING", "PAGE REPLACEMENT", "SEMAPHORE",
    "MUTEX", "CRITICAL SECTION", "THRASHING", "VIRTUAL MEMORY"
  ],
  "COMPUTER NETWORKS": ["TCP", "UDP", "OSI", "HTTP", "NETWORK"],
  "COMPILER DESIGN": [
    "COMPILER", "LEXICAL", "PARSER", "PARSING", "SYNTAX",
    "BOTTOM UP", "TOP DOWN", "SHIFT REDUCE", "GRAMMAR"
  ],
  "FRONTEND DEVELOPMENT": ["HTML", "CSS", "BOOTSTRAP"],
  "BACKEND DEVELOPMENT": ["API", "REST", "MONGODB", "BACKEND"],
  "AI/ML": ["MACHINE LEARNING", "NEURAL", "REGRESSION"]
};

export default subjectKeywords;